# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bdy < Formula
  desc "A k9s-style terminal UI for browsing beads issues"
  homepage "https://github.com/poiley/beady"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poiley/beady/releases/download/v1.0.1/bdy_darwin_amd64.tar.gz"
      sha256 "6fc2f1cf3a4742ac08986d6d6a113e89be8eb88e4893d61d149a833e4acf7d23"

      def install
        bin.install "bdy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poiley/beady/releases/download/v1.0.1/bdy_darwin_arm64.tar.gz"
      sha256 "a2e202b5f2b685719869c3da0587b401dc2662172a18e7640590771db449c8e8"

      def install
        bin.install "bdy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poiley/beady/releases/download/v1.0.1/bdy_linux_amd64.tar.gz"
      sha256 "462250b073e18df0ad13eac257ba0c23c89ae2cc9e345121f3ab894f1ce1f3cb"
      def install
        bin.install "bdy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poiley/beady/releases/download/v1.0.1/bdy_linux_arm64.tar.gz"
      sha256 "e3f22982797c9b4be8d4222d662e88f5612f4f68b51fd4d1168a7521f470380e"
      def install
        bin.install "bdy"
      end
    end
  end

  test do
    system "#{bin}/bdy", "--version"
  end
end
