# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdy" do
  name "bdy"
  desc "A k9s-style terminal UI for browsing beads issues"
  homepage "https://github.com/poiley/beady"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdy"

  on_macos do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_amd64.tar.gz"
      sha256 "f0bfacb819cae9cbd3521a5c0d8b7e4297c1ca9abc311a8991be0360cb24c3bf"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_arm64.tar.gz"
      sha256 "16ed1ee201e211643ea22809ba0297589dd8f22f861d6fe99877b9ae0ca1830d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_amd64.tar.gz"
      sha256 "86e26b452f0fe95dbb5039c65334b0b87d2f87f531a8d151edb69ecdb4af343c"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_arm64.tar.gz"
      sha256 "0c97b104f8bedc8b988b472aaa2e28f3bafac060964b4a11ea7bacc569166cff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bdy"]
    end
  end

  # No zap stanza required
end
