# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdy" do
  name "bdy"
  desc "A k9s-style terminal UI for browsing beads issues"
  homepage "https://github.com/poiley/beady"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdy"

  on_macos do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_amd64.tar.gz"
      sha256 "db91f8162ee2659ecfaa190ae6f23954538448b42e566b9cc608b5844261d7f2"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_arm64.tar.gz"
      sha256 "76f0c89be37e2da0db65db91e92947cdd472d192254fafc5ab0ebcd6a1290881"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_amd64.tar.gz"
      sha256 "6a9e08c6207b939095f7d97d53845f1ac5db83e1a396345027fe5ad4f9a821a6"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_arm64.tar.gz"
      sha256 "0999c7164dd935d7dcc71769bb4128d564863e86c4ee55d3411b78dce67d14ba"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bdy"]
    end
  end

  # No zap stanza required
end
