# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdy" do
  name "bdy"
  desc "A k9s-style terminal UI for browsing beads issues"
  homepage "https://github.com/poiley/beady"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdy"

  on_macos do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_amd64.tar.gz"
      sha256 "e5aaf8befb70f1e431f9748f7cd3cbfbd2cb77117babb2766988b9deda998816"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_darwin_arm64.tar.gz"
      sha256 "2337348245e761e2f27e400eabb993f76a639796e0f97abc7bbd941900aec58c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_amd64.tar.gz"
      sha256 "49b37723f3f27eb06f2693295ba7750fd2f7bfdb4c4cdd9ba085f8358dc7f98b"
    end
    on_arm do
      url "https://github.com/poiley/beady/releases/download/v#{version}/bdy_linux_arm64.tar.gz"
      sha256 "e345cdebecec46e12c921b0f1883d798ce654e7dc9871bfccff81831d6ca2488"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bdy"]
    end
  end

  # No zap stanza required
end
